name: Scrape and Email New Open Frontex Jobs

on:
  schedule:
    - cron: '0 9 * * *'  # Every day at 09:00 UTC
  workflow_dispatch:

jobs:
  scrape_and_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scraping script
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
      run: python scrape_email_frontex_jobs.py

    - name: Commit and push last_jobs.json if changed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add last_jobs.json

        # Check if there are any staged changes before committing
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update last_jobs.json [automated commit]"
          git push
        fi
